# Generated by Django 3.0.5 on 2022-02-05 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('program', models.CharField(max_length=2000, null=True)),
                ('batch', models.CharField(max_length=2000, null=True)),
                ('section', models.CharField(max_length=2000, null=True)),
                ('classroom', models.CharField(max_length=2000, null=True)),
                ('professor', models.CharField(max_length=2000, null=True)),
                ('day', models.CharField(max_length=2000, null=True)),
                ('start_time', models.CharField(max_length=2000, null=True)),
                ('end_time', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
