# Generated by Django 3.0.5 on 2022-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220206_1240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='section',
            new_name='centre',
        ),
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
