# Generated by Django 3.0.5 on 2022-02-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20220214_2321'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='activity',
            unique_together={('professor', 'day', 'start_time', 'end_time')},
        ),
    ]
