# Generated by Django 3.0.5 on 2022-02-06 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20220206_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
