# Generated by Django 3.0.5 on 2022-02-07 13:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20220206_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='day',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], default=0, max_length=10),
            preserve_default=False,
        ),
    ]
